cineart/movies/urls.py
from django.urls import path

from cineart.movies.views import list_movies, detail_movie

urlpatterns = [
  path("", list_movies, name="list-movie"),
  path("movie/<int:pk>", detail_movie, name="detail-movie")
]

cineart/users/urls.py
from django.urls import path

from cineart.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include("cineart.movies.urls")),
    path("users/", include("cineart.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

cineart/movies/models.py
from django.db import models


class Movie(models.Model):
    """Movie model"""

    title = models.CharField(
        "Title",
        max_length=144
    )

    description = models.TextField(
        "Description",
        max_length=800
    )

    video = models.FileField(
        "Video",
        upload_to="videos/"
    )

    poster = models.FileField(
        "Poster",
        upload_to="poster/"
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        """Return Movie Title"""

        return self.title

cineart/subtitles/models.py
from django.db import models

LANGUAGES = [
    ("es", "Spanish"),
    ("en", "English"),
    ("fr", "French")
]


class Subtitle(models.Model):
    """Subtitle Model"""

    language = models.CharField(
        "Language", 
        choices=LANGUAGES, 
        max_length=2
    )
    
    text = models.FileField(
        "Text",
        upload_to="subtitles/"
    )

    movie = models.ForeignKey(
        "movies.Movie", 
        related_name="subtitles",
        verbose_name="Movie",
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )

    def __str__(self):
        """Return Language"""

        return self.language

cineart/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

cineart/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

cineart/movies/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from cineart.movies.models import Movie


@login_required
def list_movies(request):
    """List of Movies view"""

    movies = Movie.objects.all()

    context = {
        "title": "Billboard",
        "movies": movies
    }

    return render(request, "movie/list.html", context)


@login_required
def detail_movie(request, pk):
    """Detail of a movie View"""

    movie = Movie.objects.get(id=pk)

    context = {
        "movie": movie
    }

    return render(request, "movie/detail.html", context)

cineart/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

cineart/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{% block title %}Cine Art{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />

    {% block css %}

    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link href="https://vjs.zencdn.net/7.8.3/video-js.css" rel="stylesheet" />
    <link href="{% static 'css/project.css' %}" rel="stylesheet" />

    {% endblock %}
  </head>

  <body>
    {% include 'partials/_navbar.html' %}

    <div class="container">
      {% if messages %} {% for message in messages %}
      <div
        class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}"
      >
        {{ message }}<button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %} {% endif %} {% block content %}
      <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
    </div>

    {% block modal %}{% endblock modal %} {% block javascript %}

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <script src="https://vjs.zencdn.net/7.8.3/video.js"></script>

    {% endblock javascript %}
  </body>
</html>

cineart/templates/movie/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | {{movie.title}} {%endblock %}

{% block content %}

    <div class="col-12">
      <div class="row">
        <h2 style="padding-top: 20px;">{{movie.title}}</h2>
      </div>
    </div>

    <hr />

    <video
      id="my-video"
      class="video-js vjs-default-skin vjs-fluid vjs-big-play-centered"
      controls
      preload="auto"
      width="640"
      height="264"
      poster="{{ MEDIA_URL }}{{ movie.poster }}"
      data-setup="{'fluid': true}"
    >
      <source src="{{ MEDIA_URL }}{{ movie.video }}" type="video/mp4"></source>
      {% for subtitle in movie.subtitles.all %}
        <track label="{{subtitle.language}}" kind="subtitles" srclang="{{subtitle.language}}" src="{{ MEDIA_URL }}{{ subtitle.text }}" default>
      {% endfor %}
  </video>

  <br />

  <p>{{movie.description}}</p>

{% endblock %}

cineart/templates/movie/list.html
{% extends 'base.html' %} 
{% load static %} 

{% block title %}Cine Art | {{title}} {%endblock %} 

{% block content %}

<div class="col-12">
  <div class="row">
    <h2 style="padding-top: 20px;">{{title}}</h2>
  </div>
</div>

<hr />

<div class="card-columns">
  {% for movie in movies %}
  <div class="card">
    <img src="{{ MEDIA_URL }}{{ movie.poster }}" alt="" class="card-img-top" />
    <div class="card-body">
      <h4 class="card-title">
        <a href="{% url 'detail-movie' movie.id %}">{{movie.title}}</a>
      </h4>
      <p class="card-text">{{movie.description}}</p>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

cineart/templates/pages/about.html
{% extends "base.html" %}

cineart/templates/pages/home.html
{% extends "base.html" %}

cineart/templates/partials/_navbar.html
{% load static %}

<div class="mb-3">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
      <button
        class="navbar-toggler navbar-toggler-right"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/">Cine Art</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Log out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</div>

cineart/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

cineart/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}